#!/bin/sh

set -e  # Exit on error

at_exit() {
    if $policyd ; then
       rm -f /usr/sbin/policy-rc.d
    fi
    policyd=false
}

# Make sure configuring packages do not start any services.  Also make
# sure we remove policy-rc.d only if we created it.
trap at_exit HUP INT TERM EXIT
if [ ! -e /usr/sbin/policy-rc.d ] ; then
    cat > /usr/sbin/policy-rc.d <<EOF
#!/bin/sh
exit 101
EOF
    chmod a+rx /usr/sbin/policy-rc.d
    policyd=true
else
    policyd=false
fi

for f in /usr/lib/freedombox/setup.d/* ; do
    echo "running $f"
    $f
done
